### ISSUE TITLE
Usage in the non-human assembly?

### ISSUE THREAD

**Issue by baozg** [mrvollger/SafFire#3]
Hi, @mrvollger 

Can `SafFire` use in non-human assembly ?

**Comment by mrvollger** [comment]
Sure, any PAF file from a whole genome alignment should work:
https://github.com/mrvollger/SafFire#how-to-prepare-your-genome-alignment-for-saffire

**Comment by baozg** [comment]
Thanks for promptly reply. I missed the `Load alignment data` button webpage. I can use my own data now. 
Thanks for this great tool.

**Comment by pickettbd** [comment]
@mrvollger - when I add my own data (prepared as described) with the `Load alignment data` button I still see "CHM13_v1.1" and "GRCh38" in the target and query reference fields, respectively. Is the visualization "pretending" that the coordinates I'm providing are from the target or query in those fields? Or is it using the target/query sequence sizes from the provided alignments to scale things before drawing the provided alignments?

**Comment by mrvollger** [comment]
It should be scaled to the loaded target and query sequences. I just don't have a "name" for the target and query of an uploaded bed so it stays as the defaults.

This was my first and last attempt at async JavaScript and it shows...

**Comment by pickettbd** [comment]
Thanks for clarifying! I've played with JavaScript async before - I didn't love it. The language generally annoyed me because the scoping is so weird.
