### ISSUE TITLE
questions on the dataset

### ISSUE THREAD

**Issue by WenyuLiang** [mrvollger/SafFire#4]
Hi! I wonder what _1, _2 mean? eg. HG002_1.bed and HG002_2.bed. Do they represent the results from two haplotypes?

**Comment by mrvollger** [comment]
Exactly :)

**Comment by WenyuLiang** [comment]
Thanks for replying! What tools did u use to get these phased assemblies?

**Comment by mrvollger** [comment]
The assemblies were made by the HPRC using trio HiFiasm. There will be a preprint with all the assemblies up in a few days I think.

**Comment by mrvollger** [comment]
Here's the link:

https://doi.org/10.1101/2022.07.09.499321
