### ISSUE TITLE
Visualizing genome not available on safire

### ISSUE THREAD

**Issue by okendojo** [mrvollger/SafFire#6]
I have two zebrafish genomes. How can I visualize them using this tool? I see this tool is designed to take care of human and monkey reference genomes.

**Comment by pickettbd** [comment]
@Jokendo-collab - I think it may be possible by uploading your alignments with the `Load alignment data` button (it looks like just plain text, but it is actually a button). See issue #3.

**Comment by mrvollger** [comment]
That's correct! Thanks @pickettbd
